version: "3.8"

services:
  backend:
    build: ./backend
    container_name: shred-backend
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    restart: always

  frontend:
    build: ./frontend
    container_name: shred-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: always

  mongo:
    image: mongo:6.0
    container_name: shred-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: abc123
    volumes:
      - mongo_data:/data/db
    restart: always

  mongo-express:
    image: mongo-express:1.0.2
    container_name: shred-mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: abc123
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
    depends_on:
      - mongo
    restart: always

volumes:
  mongo_data:
